# Mongo-Sync Configurations

local:
  db: 'db'
  host:
    port: 27017
  access:
    username: ''
    password: ''

remote:
  db: 'dietr-dev'
  host:
    url: 'ds052978.mlab.com'
    port: 52978
  access:
    username: 'public'
    password: 'password123'

tunnel:
  on: false
  access:
    username: 'remote_ssh_user'
    port: 22

# For now :local just
# assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail
